export default {
	"nil 020-100-MD01ba. Type_of_interval_for_a_Ylht9kCLSRW": {
		id: "Ylht9kCLSRW",
		aggregationType: "NONE",
		displayName: "100 020-100-MD01ba. Type_of_interval_for_a",
		valueType: "TEXT",
		name: "100 020-100-MD01ba. Type_of_interval_for_a",
		shortName: "nil 020-100-MD01ba. Type_of_interval_for_a",
	},
	"nil 020-100-MD02a3. Report chain of events due to_d_CnPGhOcERFF": {
		id: "CnPGhOcERFF",
		aggregationType: "NONE",
		displayName:
			"100 020-100-MD02a3. Report chain of events due to in order-Cause of death_d",
		valueType: "TEXT",
		name: "100 020-100-MD02a3. Report chain of events due to in order-Cause of death_d",
		shortName: "nil 020-100-MD02a3. Report chain of events due to_d",
	},
	"nil 020-100-MD02b1a. Type_of_interval_for_b_myydnkmLfhp": {
		id: "myydnkmLfhp",
		aggregationType: "NONE",
		displayName: "100 020-100-MD02b1a. Type_of_interval_for_b",
		valueType: "TEXT",
		name: "100 020-100-MD02b1a. Type_of_interval_for_b",
		shortName: "nil 020-100-MD02b1a. Type_of_interval_for_b",
	},
	"nil 020-100-MD02b2b. HMIS_100_Time interval_c_hO8No9fHVd2": {
		id: "hO8No9fHVd2",
		aggregationType: "NONE",
		displayName: "100 020-100-MD02b2b. HMIS_100_Time interval_c",
		valueType: "TEXT",
		name: "100 020-100-MD02b2b. HMIS_100_Time interval_c",
		shortName: "nil 020-100-MD02b2b. HMIS_100_Time interval_c",
	},
	"nil 020-100-MD02b3a. Type_of_interval_for_d_cmZrrHfTxW3": {
		id: "cmZrrHfTxW3",
		aggregationType: "NONE",
		displayName: "100 020-100-MD02b3a. Type_of_interval_for_d",
		valueType: "TEXT",
		name: "100 020-100-MD02b3a. Type_of_interval_for_d",
		shortName: "nil 020-100-MD02b3a. Type_of_interval_for_d",
	},
	"nil 020-DD03.Inpatient number_BRtcz4HV7Ak": {
		id: "BRtcz4HV7Ak",
		aggregationType: "COUNT",
		displayName: "100 020-DD03.Inpatient number",
		valueType: "TEXT",
		name: "100 020-DD03.Inpatient number",
		shortName: "nil 020-DD03.Inpatient number",
	},
	"nil 100-020. Ministry of Health National Case Number_itNUbtIXfCT": {
		id: "itNUbtIXfCT",
		aggregationType: "NONE",
		displayName: "100 100-020. Ministry of Health National Case Number",
		valueType: "TEXT",
		name: "100 100-020. Ministry of Health National Case Number",
		shortName: "nil 100-020. Ministry of Health National Case Number",
	},
	"nil 100-DD03. Nationality_yQIItb7CwT8": {
		id: "yQIItb7CwT8",
		aggregationType: "COUNT",
		displayName: "100 100-DD03. Nationality",
		valueType: "TEXT",
		name: "100 100-DD03. Nationality",
		shortName: "nil 100-DD03. Nationality",
	},
	"nil 100-DDO11. Time of Death_b6Mur4uir2M": {
		id: "b6Mur4uir2M",
		aggregationType: "COUNT",
		displayName: "100 100-DDO11. Time of Death",
		valueType: "TIME",
		name: "100 100-DDO11. Time of Death",
		shortName: "nil 100-DDO11. Time of Death",
	},
	"nil doris_underlying_cause_of_death_code_LAvyxs29laJ": {
		id: "LAvyxs29laJ",
		aggregationType: "COUNT",
		displayName: "100 doris_underlying_cause_of_death_code",
		valueType: "TEXT",
		name: "100 doris_underlying_cause_of_death_code",
		shortName: "nil doris_underlying_cause_of_death_code",
	},
	"nil doris_underlying_cause_of_death_text_tKezaEs8Ez5": {
		id: "tKezaEs8Ez5",
		aggregationType: "COUNT",
		displayName: "100 doris_underlying_cause_of_death_text",
		valueType: "TEXT",
		name: "100 doris_underlying_cause_of_death_text",
		shortName: "nil doris_underlying_cause_of_death_text",
	},
	"nil final_underlying_cause_of_death_code_n2mScmFMovq": {
		id: "n2mScmFMovq",
		aggregationType: "COUNT",
		displayName: "100 final_underlying_cause_of_death_code",
		valueType: "TEXT",
		name: "100 final_underlying_cause_of_death_code",
		shortName: "nil final_underlying_cause_of_death_code",
	},
	"nil final_underlying_cause_of_death_text_mQVAyOLbga1": {
		id: "mQVAyOLbga1",
		aggregationType: "COUNT",
		displayName: "100 final_underlying_cause_of_death_text",
		valueType: "TEXT",
		name: "100 final_underlying_cause_of_death_text",
		shortName: "nil final_underlying_cause_of_death_text",
	},
	"nil HMIS_100 Inpatient Number_FGagV1Utrdh": {
		id: "FGagV1Utrdh",
		aggregationType: "NONE",
		displayName: "100 HMIS_100 Inpatient Number",
		valueType: "TEXT",
		name: "100 HMIS_100 Inpatient Number",
		shortName: "nil HMIS_100 Inpatient Number",
	},
	" Full Name_ZYKmQ9GPOaF": {
		id: "ZYKmQ9GPOaF",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_   Full Name",
		valueType: "TEXT",
		name: "100 HMIS_100_   Full Name",
		shortName: "nil HMIS_100_   Full Name",
	},
	Age_q7e7FOXKnOf: {
		id: "q7e7FOXKnOf",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Age",
		valueType: "TEXT",
		name: "100 HMIS_100_  Age",
		shortName: "nil HMIS_100_  Age",
	},
	"Age Days_v8mvHHXo06E": {
		id: "v8mvHHXo06E",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Age Days",
		valueType: "NUMBER",
		name: "100 HMIS_100_  Age Days",
		shortName: "nil HMIS_100_  Age Days",
	},
	"Age Hours_VJXpmHCaAFG": {
		id: "VJXpmHCaAFG",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Age Hours",
		valueType: "NUMBER",
		name: "100 HMIS_100_  Age Hours",
		shortName: "nil HMIS_100_  Age Hours",
	},
	"Age Minutes_TgFI46omIEg": {
		id: "TgFI46omIEg",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Age Minutes",
		valueType: "NUMBER",
		name: "100 HMIS_100_  Age Minutes",
		shortName: "nil HMIS_100_  Age Minutes",
	},
	"Age Months_WYykJO0Vh3s": {
		id: "WYykJO0Vh3s",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Age Months",
		valueType: "NUMBER",
		name: "100 HMIS_100_  Age Months",
		shortName: "nil HMIS_100_  Age Months",
	},
	"Age of mother (years)_DdfDMFW4EJ9": {
		id: "DdfDMFW4EJ9",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Age of mother (years)",
		valueType: "TEXT",
		name: "100 HMIS_100_  Age of mother (years)",
		shortName: "nil HMIS_100_  Age of mother (years)",
	},
	Approval_twVlVWM3ffz: {
		id: "twVlVWM3ffz",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Approval",
		valueType: "TEXT",
		name: "100 HMIS_100_  Approval",
		shortName: "nil HMIS_100_  Approval",
	},
	"Birth weight (in grams)_xAWYJtQsg8M": {
		id: "xAWYJtQsg8M",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Birth weight (in grams)",
		valueType: "TEXT",
		name: "100 HMIS_100_  Birth weight (in grams)",
		shortName: "nil HMIS_100_  Birth weight (in grams)",
	},
	cause_of_death_a_uri_k9xdBQzYMXo: {
		id: "k9xdBQzYMXo",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  cause_of_death_a_uri",
		valueType: "TEXT",
		name: "100 HMIS_100_  cause_of_death_a_uri",
		shortName: "nil HMIS_100_  cause_of_death_a_uri",
	},
	cause_of_death_c_uri_fJUy96o8akn: {
		id: "fJUy96o8akn",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  cause_of_death_c_uri",
		valueType: "TEXT",
		name: "100 HMIS_100_  cause_of_death_c_uri",
		shortName: "nil HMIS_100_  cause_of_death_c_uri",
	},
	cause_of_death_d_uri_S53kx50gjQn: {
		id: "S53kx50gjQn",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  cause_of_death_d_uri",
		valueType: "TEXT",
		name: "100 HMIS_100_  cause_of_death_d_uri",
		shortName: "nil HMIS_100_  cause_of_death_d_uri",
	},
	cause_of_death_uri_b_yftBZ5bSEOb: {
		id: "yftBZ5bSEOb",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  cause_of_death_uri_b",
		valueType: "TEXT",
		name: "100 HMIS_100_  cause_of_death_uri_b",
		shortName: "nil HMIS_100_  cause_of_death_uri_b",
	},
	code_cause_of_death_a_zD0E77W4rFs: {
		id: "zD0E77W4rFs",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  code_cause_of_death_a",
		valueType: "TEXT",
		name: "100 HMIS_100_  code_cause_of_death_a",
		shortName: "nil HMIS_100_  code_cause_of_death_a",
	},
	code_cause_of_death_b_tuMMQsGtE69: {
		id: "tuMMQsGtE69",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  code_cause_of_death_b",
		valueType: "TEXT",
		name: "100 HMIS_100_  code_cause_of_death_b",
		shortName: "nil HMIS_100_  code_cause_of_death_b",
	},
	code_cause_of_death_c_C8n6hBilwsX: {
		id: "C8n6hBilwsX",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  code_cause_of_death_c",
		valueType: "TEXT",
		name: "100 HMIS_100_  code_cause_of_death_c",
		shortName: "nil HMIS_100_  code_cause_of_death_c",
	},
	code_cause_of_death_d_IeS8V8Yf40N: {
		id: "IeS8V8Yf40N",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  code_cause_of_death_d",
		valueType: "TEXT",
		name: "100 HMIS_100_  code_cause_of_death_d",
		shortName: "nil HMIS_100_  code_cause_of_death_d",
	},
	code_FINAL_underlying_cause_dTd7txVzhgY: {
		id: "dTd7txVzhgY",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  code_FINAL_underlying_cause",
		valueType: "TEXT",
		name: "100 HMIS_100_  code_FINAL_underlying_cause",
		shortName: "nil HMIS_100_  code_FINAL_underlying_cause",
	},
	county_se3wRj1bYPo: {
		id: "se3wRj1bYPo",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  county",
		valueType: "TEXT",
		name: "100 HMIS_100_  county",
		shortName: "nil HMIS_100_  county",
	},
	"Date and time of Death_i8rrl8YWxLF": {
		id: "i8rrl8YWxLF",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Date and time of Death",
		valueType: "TEXT",
		name: "100 HMIS_100_  Date and time of Death",
		shortName: "nil HMIS_100_  Date and time of Death",
	},
	"Date of Birth_RbrUuKFSqkZ": {
		id: "RbrUuKFSqkZ",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Date of Birth",
		valueType: "TEXT",
		name: "100 HMIS_100_  Date of Birth",
		shortName: "nil HMIS_100_  Date of Birth",
	},
	"Date of Injury If external cause or poi_U18Tnfz9EKd": {
		id: "U18Tnfz9EKd",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Date of Injury If external cause or poisoning",
		valueType: "TEXT",
		name: "100 HMIS_100_  Date of Injury If external cause or poisoning",
		shortName: "nil HMIS_100_  Date of Injury If external cause or poi",
	},
	"declaration(yes)_u9tYUv6AM51": {
		id: "u9tYUv6AM51",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  declaration(yes)",
		valueType: "TEXT",
		name: "100 HMIS_100_  declaration(yes)",
		shortName: "nil HMIS_100_  declaration(yes)",
	},
	"Delivered by skilled attendant_uaxjt0inPNF": {
		id: "uaxjt0inPNF",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Delivered by skilled attendant",
		valueType: "TEXT",
		name: "100 HMIS_100_  Delivered by skilled attendant",
		shortName: "nil HMIS_100_  Delivered by skilled attendant",
	},
	"Did the pregnancy contribute to the dea_AJAraEcfH63": {
		id: "AJAraEcfH63",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Did the pregnancy contribute to the death?",
		valueType: "TEXT",
		name: "100 HMIS_100_  Did the pregnancy contribute to the death?",
		shortName: "nil HMIS_100_  Did the pregnancy contribute to the dea",
	},
	District_t5nTEmlScSt: {
		id: "t5nTEmlScSt",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  District",
		valueType: "TEXT",
		name: "100 HMIS_100_  District",
		shortName: "nil HMIS_100_  District",
	},
	Examined_by_PaoRZbokFWJ: {
		id: "PaoRZbokFWJ",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Examined_by",
		valueType: "TEXT",
		name: "100 HMIS_100_  Examined_by",
		shortName: "nil HMIS_100_  Examined_by",
	},
	"For women, was the deceased pregnant?_zcn7acUB6x1": {
		id: "zcn7acUB6x1",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  For women, was the deceased pregnant?",
		valueType: "TEXT",
		name: "100 HMIS_100_  For women, was the deceased pregnant?",
		shortName: "nil HMIS_100_  For women, was the deceased pregnant?",
	},
	freetext_cause_of_death_a_cSDJ9kSJkFP: {
		id: "cSDJ9kSJkFP",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  freetext_cause_of_death_a",
		valueType: "TEXT",
		name: "100 HMIS_100_  freetext_cause_of_death_a",
		shortName: "nil HMIS_100_  freetext_cause_of_death_a",
	},
	freetext_cause_of_death_a__QHY3iYRLvMp: {
		id: "QHY3iYRLvMp",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  freetext_cause_of_death_a_",
		valueType: "TEXT",
		name: "100 HMIS_100_  freetext_cause_of_death_a_",
		shortName: "nil HMIS_100_  freetext_cause_of_death_a_",
	},
	freetext_cause_of_death_b_uckvenVFnwf: {
		id: "uckvenVFnwf",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  freetext_cause_of_death_b",
		valueType: "TEXT",
		name: "100 HMIS_100_  freetext_cause_of_death_b",
		shortName: "nil HMIS_100_  freetext_cause_of_death_b",
	},
	freetext_cause_of_death_c_ZFdJRT3PaUd: {
		id: "ZFdJRT3PaUd",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  freetext_cause_of_death_c",
		valueType: "TEXT",
		name: "100 HMIS_100_  freetext_cause_of_death_c",
		shortName: "nil HMIS_100_  freetext_cause_of_death_c",
	},
	freetext_cause_of_death_d_Op5pSvgHo1M: {
		id: "Op5pSvgHo1M",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  freetext_cause_of_death_d",
		valueType: "TEXT",
		name: "100 HMIS_100_  freetext_cause_of_death_d",
		shortName: "nil HMIS_100_  freetext_cause_of_death_d",
	},
	"I attended the deceased before death_Kz29xNOBjsJ": {
		id: "Kz29xNOBjsJ",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  I attended the deceased before death",
		valueType: "TEXT",
		name: "100 HMIS_100_  I attended the deceased before death",
		shortName: "nil HMIS_100_  I attended the deceased before death",
	},
	"I conducted the post mortem of the body_cp5xzqVU2Vw": {
		id: "cp5xzqVU2Vw",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  I conducted the post mortem of the body",
		valueType: "TEXT",
		name: "100 HMIS_100_  I conducted the post mortem of the body",
		shortName: "nil HMIS_100_  I conducted the post mortem of the body",
	},
	"I examined the body after death_ZXZZfzBpu8a": {
		id: "ZXZZfzBpu8a",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  I examined the body after death",
		valueType: "TEXT",
		name: "100 HMIS_100_  I examined the body after death",
		shortName: "nil HMIS_100_  I examined the body after death",
	},
	"If death was perinatal, please state co_GFVhltTCG8b": {
		id: "GFVhltTCG8b",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  If death was perinatal, please state conditions of mother that affected the fetus and newborn",
		valueType: "TEXT",
		name: "100 HMIS_100_  If death was perinatal, please state conditions of mother that affected the fetus and newborn",
		shortName: "nil HMIS_100_  If death was perinatal, please state co",
	},
	"If death within 24h specify number of h_jf9TogeSZpk": {
		id: "jf9TogeSZpk",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  If death within 24h specify number of hours survived",
		valueType: "TEXT",
		name: "100 HMIS_100_  If death within 24h specify number of hours survived",
		shortName: "nil HMIS_100_  If death within 24h specify number of h",
	},
	"If Other place (please specify):_mDez8j7furx": {
		id: "mDez8j7furx",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  If Other place (please specify):",
		valueType: "TEXT",
		name: "100 HMIS_100_  If Other place (please specify):",
		shortName: "nil HMIS_100_  If Other place (please specify):",
	},
	"If yes please specify date of surgery_j5TIQx3gHyF": {
		id: "j5TIQx3gHyF",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  If yes please specify date of surgery",
		valueType: "TEXT",
		name: "100 HMIS_100_  If yes please specify date of surgery",
		shortName: "nil HMIS_100_  If yes please specify date of surgery",
	},
	"If yes please specify reason for surger_JhHwdQ337nn": {
		id: "JhHwdQ337nn",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  If yes please specify reason for surgery (disease or condition)",
		valueType: "TEXT",
		name: "100 HMIS_100_  If yes please specify reason for surgery (disease or condition)",
		shortName: "nil HMIS_100_  If yes please specify reason for surger",
	},
	"If yes were the findings used in the ce_UfG52s4YcUt": {
		id: "UfG52s4YcUt",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  If yes were the findings used in the certification?",
		valueType: "TEXT",
		name: "100 HMIS_100_  If yes were the findings used in the certification?",
		shortName: "nil HMIS_100_  If yes were the findings used in the ce",
	},
	"If yes, at what point in time was decea_KpfvNQSsWIw": {
		id: "KpfvNQSsWIw",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  If yes, at what point in time was deceased pregnant?",
		valueType: "TEXT",
		name: "100 HMIS_100_  If yes, at what point in time was deceased pregnant?",
		shortName: "nil HMIS_100_  If yes, at what point in time was decea",
	},
	"Manner of death (disease)_FhHPxY16vet": {
		id: "FhHPxY16vet",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death (disease)",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death (disease)",
		shortName: "nil HMIS_100_  Manner of death (disease)",
	},
	"Manner of death - Accident_gNM2Yhypydx": {
		id: "gNM2Yhypydx",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death - Accident",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - Accident",
		shortName: "nil HMIS_100_  Manner of death - Accident",
	},
	"Manner of death - Assault_KsGOxFyzIs1": {
		id: "KsGOxFyzIs1",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death - Assault",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - Assault",
		shortName: "nil HMIS_100_  Manner of death - Assault",
	},
	"Manner of death - Could not be determin_b4yPk98om7e": {
		id: "b4yPk98om7e",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death - Could not be determined",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - Could not be determined",
		shortName: "nil HMIS_100_  Manner of death - Could not be determin",
	},
	"Manner of death - external cause or poi_AZSlwlRAFig": {
		id: "AZSlwlRAFig",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Manner of death - external cause or poisoning",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - external cause or poisoning",
		shortName: "nil HMIS_100_  Manner of death - external cause or poi",
	},
	"Manner of death - Intentional self-harm_wX3i3gkTG4m": {
		id: "wX3i3gkTG4m",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death - Intentional self-harm",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - Intentional self-harm",
		shortName: "nil HMIS_100_  Manner of death - Intentional self-harm",
	},
	"Manner of death - Legal intervention_tYH7drlbNya": {
		id: "tYH7drlbNya",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death - Legal intervention",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - Legal intervention",
		shortName: "nil HMIS_100_  Manner of death - Legal intervention",
	},
	"Manner of death - Pending investigation_fQWuywOaoN2": {
		id: "fQWuywOaoN2",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death - Pending investigation",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - Pending investigation",
		shortName: "nil HMIS_100_  Manner of death - Pending investigation",
	},
	"Manner of death - Unknown_o1hG9vr0peF": {
		id: "o1hG9vr0peF",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death - Unknown",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - Unknown",
		shortName: "nil HMIS_100_  Manner of death - Unknown",
	},
	"Manner of death - War_xDMX2CJ4Xw3": {
		id: "xDMX2CJ4Xw3",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Manner of death - War",
		valueType: "TEXT",
		name: "100 HMIS_100_  Manner of death - War",
		shortName: "nil HMIS_100_  Manner of death - War",
	},
	case_number: {
		id: "ZKBE8Xm9DJG",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Ministry of Health National Case Number",
		valueType: "TEXT",
		name: "100 HMIS_100_  Ministry of Health National Case Number",
		shortName: "nil HMIS_100_  Ministry of Health National Case Number",
	},
	"Mode of delivery_K5BDPJQk1BP": {
		id: "K5BDPJQk1BP",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Mode of delivery",
		valueType: "TEXT",
		name: "100 HMIS_100_  Mode of delivery",
		shortName: "nil HMIS_100_  Mode of delivery",
	},
	"Multiple pregnancy_V4rE1tsj5Rb": {
		id: "V4rE1tsj5Rb",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Multiple pregnancy",
		valueType: "TEXT",
		name: "100 HMIS_100_  Multiple pregnancy",
		shortName: "nil HMIS_100_  Multiple pregnancy",
	},
	NIN: {
		id: "MOstDqSY0gO",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  NIN",
		valueType: "TEXT",
		name: "100 HMIS_100_  NIN",
		shortName: "nil HMIS_100_  NIN",
	},
	"Number of completed weeks of pregnancy_lQ1Byr04JTx": {
		id: "lQ1Byr04JTx",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Number of completed weeks of pregnancy",
		valueType: "TEXT",
		name: "100 HMIS_100_  Number of completed weeks of pregnancy",
		shortName: "nil HMIS_100_  Number of completed weeks of pregnancy",
	},
	occupation: {
		id: "dsiwvNQLe5n",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Occupation",
		valueType: "TEXT",
		name: "100 HMIS_100_  Occupation",
		shortName: "nil HMIS_100_  Occupation",
	},
	"other (specify)_lu9BiHPxNqH": {
		id: "lu9BiHPxNqH",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  other (specify)",
		valueType: "TEXT",
		name: "100 HMIS_100_  other (specify)",
		shortName: "nil HMIS_100_  other (specify)",
	},
	"nil luded in brackets after the condition)_xeE5TQLvucB": {
		id: "xeE5TQLvucB",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition)",
		valueType: "TEXT",
		name: "100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition)",
		shortName: "nil luded in brackets after the condition)",
	},
	"nil ded in brackets after the condition) 2_mI0UjQioE7E": {
		id: "mI0UjQioE7E",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition) 2",
		valueType: "TEXT",
		name: "100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition) 2",
		shortName: "nil ded in brackets after the condition) 2",
	},
	"nil ded in brackets after the condition) 3_u5ebhwtAmpU": {
		id: "u5ebhwtAmpU",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition) 3",
		valueType: "TEXT",
		name: "100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition) 3",
		shortName: "nil ded in brackets after the condition) 3",
	},
	"nil ded in brackets after the condition) 4_OxJgcwH15L7": {
		id: "OxJgcwH15L7",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition) 4",
		valueType: "TEXT",
		name: "100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition) 4",
		shortName: "nil ded in brackets after the condition) 4",
	},
	"nil ded in brackets after the condition) 5_Zrn8LD3LoKY": {
		id: "Zrn8LD3LoKY",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition) 5",
		valueType: "TEXT",
		name: "100 HMIS_100_  Other significant conditions contributing to death (time intervals can be included in brackets after the condition) 5",
		shortName: "nil ded in brackets after the condition) 5",
	},
	"nil _conditions_contributing_to_death_code_ctbKSNV2cg7": {
		id: "ctbKSNV2cg7",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  other_significant_conditions_contributing_to_death_code",
		valueType: "TEXT",
		name: "100 HMIS_100_  other_significant_conditions_contributing_to_death_code",
		shortName: "nil _conditions_contributing_to_death_code",
	},
	"nil onditions_contributing_to_death_code 2_krhrEBwJeNC": {
		id: "krhrEBwJeNC",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  other_significant_conditions_contributing_to_death_code 2",
		valueType: "TEXT",
		name: "100 HMIS_100_  other_significant_conditions_contributing_to_death_code 2",
		shortName: "nil onditions_contributing_to_death_code 2",
	},
	"nil onditions_contributing_to_death_code 3_ZKtS7L49Poo": {
		id: "ZKtS7L49Poo",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  other_significant_conditions_contributing_to_death_code 3",
		valueType: "TEXT",
		name: "100 HMIS_100_  other_significant_conditions_contributing_to_death_code 3",
		shortName: "nil onditions_contributing_to_death_code 3",
	},
	"nil onditions_contributing_to_death_code 4_fJDDc9mlubU": {
		id: "fJDDc9mlubU",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  other_significant_conditions_contributing_to_death_code 4",
		valueType: "TEXT",
		name: "100 HMIS_100_  other_significant_conditions_contributing_to_death_code 4",
		shortName: "nil onditions_contributing_to_death_code 4",
	},
	"nil onditions_contributing_to_death_code 5_z89Wr84V2G6": {
		id: "z89Wr84V2G6",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  other_significant_conditions_contributing_to_death_code 5",
		valueType: "TEXT",
		name: "100 HMIS_100_  other_significant_conditions_contributing_to_death_code 5",
		shortName: "nil onditions_contributing_to_death_code 5",
	},
	Parity_ymyLrfEcYkD: {
		id: "ymyLrfEcYkD",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Parity",
		valueType: "TEXT",
		name: "100 HMIS_100_  Parity",
		shortName: "nil HMIS_100_  Parity",
	},
	"Place of Death_xNCSFrgdUgi": {
		id: "xNCSFrgdUgi",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Place of Death",
		valueType: "TEXT",
		name: "100 HMIS_100_  Place of Death",
		shortName: "nil HMIS_100_  Place of Death",
	},
	"Place of delivery_Z41di0TRjIu": {
		id: "Z41di0TRjIu",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Place of delivery",
		valueType: "TEXT",
		name: "100 HMIS_100_  Place of delivery",
		shortName: "nil HMIS_100_  Place of delivery",
	},
	"Place of occurrence of the external cau_kGIDD5xIeLC": {
		id: "kGIDD5xIeLC",
		aggregationType: "NONE",
		displayName: "100 HMIS_100_  Place of occurrence of the external cause",
		valueType: "TEXT",
		name: "100 HMIS_100_  Place of occurrence of the external cause",
		shortName: "nil HMIS_100_  Place of occurrence of the external cau",
	},
	"Please describe how external cause occu_DKlOhZJOCrX": {
		id: "DKlOhZJOCrX",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Please describe how external cause occurred (If poisoning please specify poisoning agent)",
		valueType: "TEXT",
		name: "100 HMIS_100_  Please describe how external cause occurred (If poisoning please specify poisoning agent)",
		shortName: "nil HMIS_100_  Please describe how external cause occu",
	},
	"Referred from (level of care)_RJhbkjYrODG": {
		id: "RJhbkjYrODG",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Referred from (level of care)",
		valueType: "TEXT",
		name: "100 HMIS_100_  Referred from (level of care)",
		shortName: "nil HMIS_100_  Referred from (level of care)",
	},
	"Report chain of events -due to� in or_zb7uTuBCPrN": {
		id: "zb7uTuBCPrN",
		aggregationType: "NONE",
		displayName:
			"100 HMIS_100_  Report chain of events -due to� in order-Cause of death_b",
		valueType: "TEXT",
		name: "100 HMIS_100_  Report chain of events -due to� in order-Cause of death_b",
		shortName: "nil HMIS_100_  Report chain of events -due to� in or",
	},
	"Report disease or condition directly le_sfpqAeqKeyQ": {
		id: "sfpqAeqKeyQ",
		aggregationType: "NONE",
		displayName:
			"100 HMIS_100_  Report disease or condition directly leading to death-Cause of death_a",
		valueType: "TEXT",
		name: "100 HMIS_100_  Report disease or condition directly leading to death-Cause of death_a",
		shortName: "nil HMIS_100_  Report disease or condition directly le",
	},
	Sex_e96GB4CXyd3: {
		id: "e96GB4CXyd3",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Sex",
		valueType: "TEXT",
		name: "100 HMIS_100_  Sex",
		shortName: "nil HMIS_100_  Sex",
	},
	"State the underlying cause_FINAL_on the_QTKk2Xt8KDu": {
		id: "QTKk2Xt8KDu",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  State the underlying cause_FINAL_on the lowest used line",
		valueType: "TEXT",
		name: "100 HMIS_100_  State the underlying cause_FINAL_on the lowest used line",
		shortName: "nil HMIS_100_  State the underlying cause_FINAL_on the",
	},
	state_the_underlying_cause_uri_L97MrANAav9: {
		id: "L97MrANAav9",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  state_the_underlying_cause_uri",
		valueType: "TEXT",
		name: "100 HMIS_100_  state_the_underlying_cause_uri",
		shortName: "nil HMIS_100_  state_the_underlying_cause_uri",
	},
	state_the_underlying_cause_uri_final_L97MrAMAav9: {
		id: "L97MrAMAav9",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  state_the_underlying_cause_uri_final",
		valueType: "TEXT",
		name: "100 HMIS_100_  state_the_underlying_cause_uri_final",
		shortName: "nil HMIS_100_  state_the_underlying_cause_uri_final",
	},
	"Stillborn?_ivnHp4M4hFF": {
		id: "ivnHp4M4hFF",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Stillborn?",
		valueType: "TEXT",
		name: "100 HMIS_100_  Stillborn?",
		shortName: "nil HMIS_100_  Stillborn?",
	},
	"Time interval_a_WkXxkKEJLsg": {
		id: "WkXxkKEJLsg",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Time interval_a",
		valueType: "TEXT",
		name: "100 HMIS_100_  Time interval_a",
		shortName: "nil HMIS_100_  Time interval_a",
	},
	"Time interval_d_eCVDO6lt4go": {
		id: "eCVDO6lt4go",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Time interval_d",
		valueType: "TEXT",
		name: "100 HMIS_100_  Time interval_d",
		shortName: "nil HMIS_100_  Time interval_d",
	},
	URI_Field_T4uxg60Lalw: {
		id: "T4uxg60Lalw",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  URI_Field",
		valueType: "TEXT",
		name: "100 HMIS_100_  URI_Field",
		shortName: "nil HMIS_100_  URI_Field",
	},
	"Usual Residence-County_b70okb06FWa": {
		id: "b70okb06FWa",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Usual Residence-County",
		valueType: "TEXT",
		name: "100 HMIS_100_  Usual Residence-County",
		shortName: "nil HMIS_100_  Usual Residence-County",
	},
	"Usual Residence-Parish_bNpMzyShDCX": {
		id: "bNpMzyShDCX",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Usual Residence-Parish",
		valueType: "TEXT",
		name: "100 HMIS_100_  Usual Residence-Parish",
		shortName: "nil HMIS_100_  Usual Residence-Parish",
	},
	"Usual Residence-Sub-County_u44XP9fZweA": {
		id: "u44XP9fZweA",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Usual Residence-Sub-County",
		valueType: "TEXT",
		name: "100 HMIS_100_  Usual Residence-Sub-County",
		shortName: "nil HMIS_100_  Usual Residence-Sub-County",
	},
	"Usual Residence-Village_zwKo51BEayZ": {
		id: "zwKo51BEayZ",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Usual Residence-Village",
		valueType: "TEXT",
		name: "100 HMIS_100_  Usual Residence-Village",
		shortName: "nil HMIS_100_  Usual Residence-Village",
	},
	"Was an autopsy requested?_jY3K6Bv4o9Q": {
		id: "jY3K6Bv4o9Q",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_  Was an autopsy requested?",
		valueType: "TEXT",
		name: "100 HMIS_100_  Was an autopsy requested?",
		shortName: "nil HMIS_100_  Was an autopsy requested?",
	},
	"Was surgery performed within the last 4_Kk0hmrJPR90": {
		id: "Kk0hmrJPR90",
		aggregationType: "COUNT",
		displayName:
			"100 HMIS_100_  Was surgery performed within the last 4 weeks?",
		valueType: "TEXT",
		name: "100 HMIS_100_  Was surgery performed within the last 4 weeks?",
		shortName: "nil HMIS_100_  Was surgery performed within the last 4",
	},
	"nil HMIS_100_ Event Date_W0r4m6NiLsy": {
		id: "W0r4m6NiLsy",
		aggregationType: "NONE",
		displayName: "100 HMIS_100_ Event Date",
		valueType: "TEXT",
		name: "100 HMIS_100_ Event Date",
		shortName: "nil HMIS_100_ Event Date",
	},
	"nil HMIS_100_Linked_ZkNDFfFSTYg": {
		id: "ZkNDFfFSTYg",
		aggregationType: "NONE",
		displayName: "100 HMIS_100_Linked",
		valueType: "TEXT",
		name: "100 HMIS_100_Linked",
		shortName: "nil HMIS_100_Linked",
	},
	"nil HMIS_100_Report chain of events -due to_QGFYJK00ES7": {
		id: "QGFYJK00ES7",
		aggregationType: "NONE",
		displayName:
			"100 HMIS_100_Report chain of events -due to� in order-Cause of death_c",
		valueType: "TEXT",
		name: "100 HMIS_100_Report chain of events -due to� in order-Cause of death_c",
		shortName: "nil HMIS_100_Report chain of events -due to",
	},
	"nil HMIS_100_Time interval_b_fleGy9CvHYh": {
		id: "fleGy9CvHYh",
		aggregationType: "COUNT",
		displayName: "100 HMIS_100_Time interval_b",
		valueType: "TEXT",
		name: "100 HMIS_100_Time interval_b",
		shortName: "nil HMIS_100_Time interval_b",
	},
	"nil HMIS_100_Type_of_interval_for_c_aC64sB86ThG": {
		id: "aC64sB86ThG",
		aggregationType: "NONE",
		displayName: "100 HMIS_100_Type_of_interval_for_c",
		valueType: "TEXT",
		name: "100 HMIS_100_Type_of_interval_for_c",
		shortName: "nil HMIS_100_Type_of_interval_for_c",
	},
	"nil HMIS_100_unmapped_sJhOdGLD5lj": {
		id: "sJhOdGLD5lj",
		aggregationType: "NONE",
		displayName: "100 HMIS_100_unmapped",
		valueType: "TEXT",
		name: "100 HMIS_100_unmapped",
		shortName: "nil HMIS_100_unmapped",
	},
};
